# render.yaml
services:
  - type: web
    name: like-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_URL
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: ALLOWED_GROUP_ID
        sync: false
      - key: VIDEO_HOST_URL
        sync: false
