# render.yaml
services:
  - type: web
    name: like-bot-auto
    runtime: python
    repo: https://github.com/likebotf286-debug/like-bot-auto
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8307741402:AAG0QNCV4Qr_GDSk0uSPgfjSotkVfugkNEw  # Replace with your actual token
      - key: GROUP_ID
        value: -1003765179070  # Replace with your group ID
      - key: ADMIN_IDS
        value: 6417430059  # Replace with your admin IDs
      - key: API_URL
        value: https://like-api-frexy.up.railway.app/like?uid={}&server_name={}
      - key: MEDIA_URL
        value: https://sharevideo.org/fOBSNh1xZy7IJoG/watch
      - key: PYTHON_VERSION
        value: 3.9.0
